name: CI
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Ensure pnpm lock file
        run: |
          ls -la

      - name: Install Dependencies
        run: |
          export PATH=$(npm bin -g):$PATH
          pnpm install --no-frozen-lockfile
      
      - name: Set LIBGL_ALWAYS_INDIRECT
        run: echo "LIBGL_ALWAYS_INDIRECT=1" >> $GITHUB_ENV

      - name: Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          start: 'npm run dev'
          build: 'npm run build'
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress Result
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore
