name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'  
          cache: 'pnpm'
          cache-dependency-path: examples/basic-pnpm/pnpm-lock.yaml

      - name: Install pnpm
        run: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            export PATH="$HOME/.local/share/pnpm:$HOME/.pnpm-global/5/bin:$PATH"
            pnpm --version
  
      - name: Install dependencies
        run: pnpm install
        
      - uses: cypress-io/github-action@v6
        with:
          start: 'npm run dev'
          build: 'npm run build'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress Result
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore